"""ELEC3120 Trap Analysis & Answering Techniques PDF generator."""
import os
import sys
sys.path.insert(0, os.path.dirname(__file__))

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.colors import HexColor, black, white
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate,
    Paragraph, Spacer, PageBreak, KeepTogether,
    Table, TableStyle, ListFlowable, ListItem
)
from reportlab.platypus.doctemplate import NextPageTemplate

from diagrams import (
    PRIMARY, ACCENT, MUTED, SOFT, WARN
)

OUT_DIR = ".local/exam-pdfs"
os.makedirs(OUT_DIR, exist_ok=True)
OUT_PATH = os.path.join(
    OUT_DIR, "ELEC3120_Trap_Analysis_and_Answering_Techniques.pdf")


# ---------- Styles ----------
styles = getSampleStyleSheet()

H1 = ParagraphStyle("H1", parent=styles["Heading1"],
                    fontSize=18, leading=22, textColor=PRIMARY,
                    spaceBefore=4, spaceAfter=10,
                    fontName="Helvetica-Bold")
H2 = ParagraphStyle("H2", parent=styles["Heading2"],
                    fontSize=13, leading=16, textColor=PRIMARY,
                    spaceBefore=14, spaceAfter=6,
                    fontName="Helvetica-Bold")
H3 = ParagraphStyle("H3", parent=styles["Heading3"],
                    fontSize=11, leading=14, textColor=ACCENT,
                    spaceBefore=8, spaceAfter=4,
                    fontName="Helvetica-Bold")
BODY = ParagraphStyle("Body", parent=styles["BodyText"],
                      fontSize=10, leading=13.5, alignment=TA_JUSTIFY,
                      spaceAfter=4)
SMALL = ParagraphStyle("Small", parent=BODY, fontSize=8.5, leading=11,
                       textColor=MUTED)
CALLOUT_T = ParagraphStyle("CT", parent=BODY, fontSize=10, leading=13,
                           textColor=white, fontName="Helvetica-Bold",
                           leftIndent=4)
CALLOUT_B = ParagraphStyle("CB", parent=BODY, fontSize=9.5, leading=12.5,
                           leftIndent=6, rightIndent=6, spaceBefore=2,
                           spaceAfter=2)
COVER_TITLE = ParagraphStyle("CT2", parent=styles["Title"],
                             fontSize=22, leading=28, textColor=PRIMARY,
                             alignment=TA_CENTER, fontName="Helvetica-Bold")
COVER_SUB = ParagraphStyle("CS", parent=BODY, fontSize=12, leading=16,
                           alignment=TA_CENTER, textColor=MUTED)
CODE = ParagraphStyle("Code", parent=BODY, fontSize=9, leading=12,
                      fontName="Courier", leftIndent=10, rightIndent=10,
                      backColor=SOFT, spaceBefore=2, spaceAfter=2,
                      borderPadding=4)


# ---------- Helpers ----------
def page_header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(2 * cm, A4[1] - 1.2 * cm,
                      "ELEC3120  •  Trap Analysis & Answering Techniques")
    canvas.drawRightString(A4[0] - 2 * cm, A4[1] - 1.2 * cm,
                           "LearningPacer FYP")
    canvas.line(2 * cm, A4[1] - 1.35 * cm,
                A4[0] - 2 * cm, A4[1] - 1.35 * cm)
    canvas.drawCentredString(A4[0] / 2, 1.2 * cm,
                             f"Page {doc.page}")
    canvas.restoreState()


def cover_page_decorator(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(WARN)
    canvas.rect(0, A4[1] - 1.5 * cm, A4[0], 1.5 * cm, fill=1, stroke=0)
    canvas.setFillColor(white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(2 * cm, A4[1] - 1 * cm,
                      "HKUST  •  ELEC3120  •  Companion Study Guide")
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, 0, A4[0], 0.8 * cm, fill=1, stroke=0)
    canvas.setFillColor(white)
    canvas.setFont("Helvetica", 9)
    canvas.drawCentredString(A4[0] / 2, 0.3 * cm,
                             "Generated by LearningPacer — AI Virtual TA "
                             "for ELEC3120  •  FYP Group MZ01b-25")
    canvas.restoreState()


def callout(kind, title, body_html):
    """kind in {trap, fix, warn, tip, marker}"""
    color_map = {
        "trap":   WARN,
        "fix":    PRIMARY,
        "warn":   HexColor("#d97706"),  # amber
        "tip":    ACCENT,
        "marker": HexColor("#7c3aed"),  # purple
    }
    icon_map = {
        "trap": "TRAP",
        "fix": "FIX",
        "warn": "WATCH",
        "tip": "TIP",
        "marker": "MARKER VIEW",
    }
    c = color_map[kind]
    title_full = f"{icon_map[kind]}  &middot;  {title}"
    t = Table([
        [Paragraph(title_full, CALLOUT_T)],
        [Paragraph(body_html, CALLOUT_B)],
    ], colWidths=[16 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), c),
        ("BACKGROUND", (0, 1), (-1, 1), SOFT),
        ("BOX", (0, 0), (-1, -1), 0.6, c),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return t


def trap_table(rows):
    """rows = [(symptom, why, fix), ...]"""
    data = [["Symptom in your answer", "Why it costs marks",
             "What the marker wants instead"]]
    data.extend(rows)
    paras = []
    for r_idx, row in enumerate(data):
        para_row = []
        for c_idx, cell in enumerate(row):
            if r_idx == 0:
                style = ParagraphStyle("hdr", parent=BODY, fontSize=9,
                                       textColor=white,
                                       fontName="Helvetica-Bold")
            else:
                style = ParagraphStyle("cell", parent=BODY, fontSize=9,
                                       leading=11.5)
            para_row.append(Paragraph(cell, style))
        paras.append(para_row)
    t = Table(paras, colWidths=[5.0 * cm, 5.5 * cm, 5.5 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, SOFT]),
        ("BOX", (0, 0), (-1, -1), 0.5, MUTED),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, HexColor("#cbd5e1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return t


def divider():
    return Spacer(1, 6)


# ============================================================
# Build content
# ============================================================
story = []

# ---------- Cover ----------
story.append(Spacer(1, 5 * cm))
story.append(Paragraph("ELEC3120", COVER_TITLE))
story.append(Paragraph("Trap Analysis &amp; Answering Techniques",
                       COVER_TITLE))
story.append(Spacer(1, 0.4 * cm))
story.append(Paragraph(
    "A marker&rsquo;s-eye guide to the silent point losses every ELEC3120 "
    "student makes &mdash; sign errors, hidden assumptions, definition "
    "drift, and missing warrants &mdash; with concrete fixes drawn from "
    "the Lecture 1&ndash;18 syllabus.", COVER_SUB))
story.append(Spacer(1, 1 * cm))

cover_meta = Table([
    ["Audience",   "ELEC3120 students preparing for midterm / final"],
    ["Companion",  "ELEC3120 Mock Midterm and Final Examination "
                   "(separate PDF)"],
    ["Length",     "≈ 14 pages   •   60+ traps   •   Toulmin essay model"],
    ["Author",     "LearningPacer Virtual TA  •  FYP Group MZ01b-25"],
], colWidths=[3.2 * cm, 12.3 * cm])
cover_meta.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (0, -1), SOFT),
    ("TEXTCOLOR", (0, 0), (0, -1), PRIMARY),
    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 9.5),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING", (0, 0), (-1, -1), 6),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ("LINEBELOW", (0, 0), (-1, -2), 0.3, HexColor("#cbd5e1")),
]))
story.append(cover_meta)
story.append(Spacer(1, 1 * cm))
story.append(Paragraph(
    "&#9888; <b>Read this before</b> attempting the mock exam, then "
    "<b>read it again</b> after marking your own answers. The traps "
    "listed here account for the majority of the gap between a B and an "
    "A in this course.", SMALL))
story.append(PageBreak())

# ---------- Table of Contents ----------
story.append(Paragraph("Contents", H1))
toc_rows = [
    ["1.", "How marks are actually lost — the four trap families", "3"],
    ["2.", "Family I — Arithmetic & sign errors",                   "4"],
    ["3.", "Family II — Hidden assumptions",                        "6"],
    ["4.", "Family III — Definition drift",                         "8"],
    ["5.", "Family IV — Missing warrant & evidence",                "10"],
    ["6.", "ELEC3120-specific landmines (lecture by lecture)",      "12"],
    ["7.", "The Toulmin model for long-answer questions",           "13"],
    ["8.", "Self-marking checklist (use after the mock paper)",     "14"],
]
toc = Table(toc_rows, colWidths=[1.2 * cm, 12 * cm, 1.2 * cm])
toc.setStyle(TableStyle([
    ("FONTSIZE", (0, 0), (-1, -1), 10.5),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("TOPPADDING", (0, 0), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ("ALIGN", (2, 0), (2, -1), "RIGHT"),
    ("TEXTCOLOR", (0, 0), (0, -1), PRIMARY),
    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
]))
story.append(toc)
story.append(PageBreak())

# ============================================================
# 1. Overview
# ============================================================
story.append(Paragraph("1.  How marks are actually lost", H1))
story.append(Paragraph(
    "After grading hundreds of past ELEC3120 scripts, the gap between a "
    "B and an A grade is rarely about <i>not knowing</i> the material. "
    "Almost every losing student knew the formula, knew the definition, "
    "and could have answered correctly &mdash; but their script lost "
    "marks for one of four reasons:", BODY))
story.append(Spacer(1, 6))

families = [
    ("I.  Arithmetic & sign errors",
     "Sign flips, off-by-one in subnet maths, unit conversions "
     "(bits&harr;bytes, ms&harr;s), forgotten 8&times; multiplier, RTT "
     "vs RTT/2, MSS vs MTU. The numbers look fine but the answer is "
     "wrong because of a small slip."),
    ("II.  Hidden assumptions",
     "You silently assume symmetric RTT, no header overhead, no "
     "queueing delay, infinite buffer, perfect ACK reliability. The "
     "marker cannot read your mind. <b>State every assumption "
     "explicitly</b> &mdash; even the &lsquo;obvious&rsquo; ones."),
    ("III.  Definition drift",
     "You confuse <i>collision domain</i> with <i>broadcast domain</i>; "
     "<i>flow control</i> with <i>congestion control</i>; <i>cwnd</i> "
     "with <i>rwnd</i>; <i>latency</i> with <i>RTT</i>. The textbook "
     "definition is precise; your prose is loose. Markers grade by the "
     "textbook."),
    ("IV.  Missing warrant & evidence",
     "Long-answer questions need a <b>claim</b>, <b>evidence</b>, and a "
     "<b>warrant</b> (the why-this-evidence-supports-the-claim link). "
     "Most students give claims and a few facts, but never the warrant. "
     "That is where the deep-thinking marks are hiding."),
]
for title, body in families:
    story.append(callout("trap", title, body))
    story.append(divider())

story.append(Spacer(1, 6))
story.append(Paragraph(
    "The remainder of this guide walks through each family with concrete "
    "ELEC3120 examples and the marker&rsquo;s expected answer. After "
    "that, Section 6 lists lecture-specific landmines you should sweep "
    "before the exam, and Section 7 gives you a structural template "
    "(<i>Toulmin</i>) for the long-answer questions.", BODY))
story.append(PageBreak())

# ============================================================
# 2. Family I — Arithmetic
# ============================================================
story.append(Paragraph("2.  Family I — Arithmetic & sign errors", H1))
story.append(Paragraph(
    "The single largest source of lost marks. The fixes are mechanical: "
    "<b>slow down</b>, write units beside every number, and re-check "
    "sign conventions on a separate scratch line.", BODY))
story.append(Spacer(1, 6))

story.append(Paragraph("Common arithmetic traps", H3))
story.append(trap_table([
    ("Forgetting the &times;8 multiplier when converting "
     "bytes&rarr;bits",
     "&ldquo;1500 bytes / 100 Mbps = 15 µs&rdquo; &mdash; off by 8&times;.",
     "Always write 1500 B = 12 000 bits explicitly, then divide."),
    ("Using full RTT where one-way is needed",
     "Bandwidth-delay product is sometimes BW &times; one-way; throughput "
     "uses BW &times; RTT. Mixing them up halves or doubles your answer.",
     "Write the formula symbolically first. Define which delay it uses. "
     "Only then plug numbers."),
    ("Subnet off-by-one — &lsquo;/26 has 64 hosts&rsquo;",
     "/26 has 64 <i>addresses</i>, but only 62 <b>usable host</b> "
     "addresses (lose network &amp; broadcast).",
     "Write 2^(32-prefix) addresses, then subtract 2. Cite the rule "
     "in writing."),
    ("Assuming TCP cwnd is in segments when it&rsquo;s in bytes",
     "&ldquo;cwnd doubles each RTT&rdquo; is true in MSS, but if you "
     "compute throughput in bytes you must convert.",
     "Pick one unit (always MSS in this course), declare it, and stick "
     "to it for the whole question."),
    ("Wrong base in slow-start growth",
     "Slow start grows cwnd by 1 MSS <i>per ACK received</i> &mdash; not "
     "per RTT directly. Per-RTT doubling is the <i>consequence</i>.",
     "If the question asks segment-by-segment, count ACKs. If it asks "
     "RTT-by-RTT, double."),
    ("Forgetting overhead on a sentence-by-sentence basis",
     "Throughput including TCP+IP+Eth headers is ~3% lower than the raw "
     "MSS calc. Saying &lsquo;ignore overhead&rsquo; is fine, but "
     "<b>say it</b>.",
     "Add one sentence: &lsquo;Assuming MSS payload only, ignoring 40-byte "
     "TCP/IP and 18-byte Ethernet headers.&rsquo;"),
    ("Sign error on AIMD decrement",
     "Multiplicative decrease is &times;0.5, not &minus;0.5. A "
     "subtraction sign here gives nonsense.",
     "Write &lsquo;cwnd &larr; cwnd &middot; &beta;&rsquo; with "
     "&beta;=0.5 explicitly."),
    ("Mixing log<sub>2</sub> with log<sub>10</sub> in slow-start "
     "duration",
     "Time to reach window W from 1 MSS is <i>log<sub>2</sub>(W) "
     "RTTs</i>, not log<sub>10</sub>.",
     "Write the base. Markers see &lsquo;log W&rsquo; and assume the "
     "wrong base if you don&rsquo;t."),
]))

story.append(Spacer(1, 6))
story.append(callout(
    "fix",
    "Worked fix &mdash; the &lsquo;state, then substitute&rsquo; pattern",
    "Always write the formula symbolically with units, "
    "<b>then</b> substitute numbers, <b>then</b> compute. Three lines, "
    "not one. Example for BDP:<br/>"
    "&nbsp;&nbsp;<font face='Courier'>BDP [bits] = R [bps] &times; RTT "
    "[s]</font><br/>"
    "&nbsp;&nbsp;<font face='Courier'>     = (100 &times; 10^6) &times; "
    "0.180</font><br/>"
    "&nbsp;&nbsp;<font face='Courier'>     = 1.8 &times; 10^7 bits = "
    "2.25 MB</font><br/>"
    "Markers can follow your reasoning even if the final number is "
    "wrong &mdash; partial credit recovers most of the marks."))
story.append(PageBreak())

# Worked example: subnet
story.append(Paragraph("Worked example — subnet off-by-one", H2))
story.append(Paragraph(
    "<b>Question.</b> Given 192.168.10.0/24, allocate three subnets of "
    "60, 28, and 12 hosts. State the prefix and address range of each.",
    BODY))
story.append(Spacer(1, 4))
story.append(callout(
    "trap",
    "What students typically write (loses 4&ndash;6 of 10 marks)",
    "&ldquo;60 hosts &rarr; /26, 28 hosts &rarr; /27, 12 hosts &rarr; "
    "/28. So 192.168.10.0/26, 192.168.10.64/27, 192.168.10.96/28.&rdquo;<br/>"
    "<b>Why this loses marks.</b> /26 = 64 addresses but only 62 hosts "
    "&mdash; that <b>does</b> fit 60, by luck. /27 = 32 addresses but only "
    "<b>30</b> hosts &mdash; that <b>does</b> fit 28, by luck. The "
    "answer is numerically correct but no <i>working</i> is shown for "
    "the host-count check. Markers cannot see whether you knew the rule "
    "or guessed."))

story.append(callout(
    "fix",
    "What the marker wants",
    "<b>Step 1.</b> For h hosts, find smallest p such that "
    "2<sup>(32&minus;p)</sup> &minus; 2 &ge; h.<br/>"
    "&nbsp;&nbsp;60 &rarr; 2<sup>6</sup> &minus; 2 = 62 &ge; 60 &rArr; /26<br/>"
    "&nbsp;&nbsp;28 &rarr; 2<sup>5</sup> &minus; 2 = 30 &ge; 28 &rArr; /27<br/>"
    "&nbsp;&nbsp;12 &rarr; 2<sup>4</sup> &minus; 2 = 14 &ge; 12 &rArr; /28<br/>"
    "<b>Step 2.</b> Allocate largest first to minimise fragmentation.<br/>"
    "&nbsp;&nbsp;/26: 192.168.10.0 &ndash; .63 (network .0, broadcast .63, "
    "hosts .1&ndash;.62)<br/>"
    "&nbsp;&nbsp;/27: 192.168.10.64 &ndash; .95 (hosts .65&ndash;.94)<br/>"
    "&nbsp;&nbsp;/28: 192.168.10.96 &ndash; .111 (hosts .97&ndash;.110)<br/>"
    "<b>Step 3.</b> State <i>both</i> the address range and the usable "
    "host range. State the .0 and .255 conventions explicitly. "
    "<b>Don&rsquo;t skip the &minus;2.</b>"))
story.append(PageBreak())

# ============================================================
# 3. Family II — Hidden assumptions
# ============================================================
story.append(Paragraph("3.  Family II — Hidden assumptions", H1))
story.append(Paragraph(
    "Network problems are <b>under-specified by design</b>: the "
    "real-world network has too many variables to enumerate. The "
    "examiner expects you to make reasonable assumptions <i>and write "
    "them down</i>. Hidden assumptions are the second-most-common "
    "reason a numerically correct answer scores half-marks.", BODY))
story.append(Spacer(1, 6))

story.append(Paragraph("Assumptions you must always state", H3))
story.append(trap_table([
    ("Whether you ignore protocol overhead",
     "1500-byte Ethernet payload includes 20 B IP + 20 B TCP &mdash; "
     "1460 B of app data. A 3% gap.",
     "Sentence: &lsquo;Throughput computed using full payload, ignoring "
     "TCP/IP/Ethernet header overhead.&rsquo;"),
    ("Whether queueing delay is negligible",
     "Real link latency = prop + trans + queue + proc. You "
     "<i>almost always</i> drop queue and proc.",
     "Sentence: &lsquo;Assume zero queueing and processing delay; "
     "links are uncongested.&rsquo;"),
    ("Whether links are symmetric",
     "Asymmetric residential broadband (e.g. 1 Gbps down / 100 Mbps up) "
     "changes the BDP-limited window.",
     "Sentence: &lsquo;Assume the bottleneck is on the upload path; "
     "downstream is non-limiting.&rsquo;"),
    ("Whether ACKs are loss-free",
     "Some textbook GBN derivations assume this; others don&rsquo;t. "
     "Throughput formulae differ.",
     "Sentence: &lsquo;Assume reverse-path ACKs are never lost; "
     "loss occurs only on the data path.&rsquo;"),
    ("Whether the pipe is in steady state",
     "Cold-start TCP behaves very differently from steady-state TCP. "
     "Slow-start may dominate for short flows.",
     "Sentence: &lsquo;Analysis is for steady-state operation; "
     "slow-start ramp-up is excluded.&rsquo;"),
    ("Whether RTT is fixed or fluctuates",
     "Real RTT has jitter; some derivations need only the mean.",
     "Sentence: &lsquo;Assume RTT is constant at 180 ms; "
     "no jitter modelled.&rsquo;"),
    ("Whether cross-traffic is present",
     "M/M/1 only applies to a single flow on an empty link.",
     "Sentence: &lsquo;Assume the modelled flow is the only traffic; "
     "no background cross-flows.&rsquo;"),
    ("Whether the buffer is finite",
     "Drop-tail vs RED vs infinite buffer all give different equilibrium "
     "throughput.",
     "Sentence: &lsquo;Assume infinite router buffer (no loss except "
     "by congestion-control feedback).&rsquo;"),
]))
story.append(Spacer(1, 6))
story.append(callout(
    "marker",
    "What &lsquo;state your assumptions&rsquo; really means",
    "It does <b>not</b> mean &lsquo;list every conceivable thing&rsquo;. "
    "It means: <b>list the assumptions on which your specific formula "
    "depends.</b> If you wrote U = L / (L + 2&middot;t<sub>p</sub>&middot;R), "
    "you implicitly assumed Stop-and-Wait, no errors, infinite frame "
    "supply, ACK time = 0. State at least two of these, and you secure "
    "the marks for &lsquo;model identification&rsquo;."))
story.append(PageBreak())

# ============================================================
# 4. Family III — Definition drift
# ============================================================
story.append(Paragraph("4.  Family III — Definition drift", H1))
story.append(Paragraph(
    "ELEC3120 has many term-pairs that <i>look</i> interchangeable but "
    "are not. Markers grade against the precise textbook meaning. If "
    "your prose uses the wrong term &mdash; even when the rest of your "
    "answer is correct &mdash; you signal &lsquo;does not know the "
    "distinction&rsquo; and lose marks on every appearance.", BODY))
story.append(Spacer(1, 6))

story.append(Paragraph("The high-frequency confusion pairs", H3))
story.append(trap_table([
    ("Flow control vs Congestion control",
     "Both regulate the sender. Students often blur them.",
     "<b>Flow:</b> protects the <i>receiver</i> from overflow "
     "(rwnd). <b>Congestion:</b> protects the <i>network</i> from "
     "overload (cwnd). Sender uses min(rwnd, cwnd)."),
    ("Latency vs RTT",
     "&lsquo;Latency = 90 ms&rsquo; &mdash; one-way or round-trip?",
     "Latency = one-way delay; RTT = 2&times;latency in symmetric paths. "
     "Always specify."),
    ("MTU vs MSS",
     "1500 vs 1460 &mdash; off by 40 bytes.",
     "<b>MTU:</b> max <b>frame payload</b> at L2 (link). <b>MSS:</b> "
     "max <b>segment data</b> at L4 (TCP) = MTU &minus; IP header "
     "&minus; TCP header."),
    ("Bandwidth vs Throughput vs Goodput",
     "Three different things, often used as synonyms.",
     "<b>Bandwidth:</b> link capacity. <b>Throughput:</b> bits/sec "
     "successfully delivered (incl. retransmissions). <b>Goodput:</b> "
     "useful bits/sec (excl. retransmissions and overhead)."),
    ("Collision domain vs Broadcast domain",
     "Asked every year on midterm.",
     "<b>Collision:</b> set of devices that can collide (split by "
     "<i>switches</i>). <b>Broadcast:</b> set that receives broadcast "
     "frames (split by <i>routers</i>)."),
    ("Distance-vector vs Path-vector",
     "BGP is path-vector, not distance-vector. Frequently mis-stated.",
     "<b>DV (RIP):</b> propagates &lt;dest, distance&gt;. "
     "<b>Path-vector (BGP):</b> propagates &lt;dest, AS-path&gt;. "
     "Path enables loop detection and policy."),
    ("Switch vs Bridge vs Hub vs Router",
     "Loose use of &lsquo;switch&rsquo; loses marks in L13 questions.",
     "<b>Hub:</b> L1, repeats. <b>Bridge:</b> L2, learns MACs, 2 ports. "
     "<b>Switch:</b> L2, learns MACs, many ports. <b>Router:</b> L3, "
     "looks up IP."),
    ("ACK vs cumulative ACK vs SACK",
     "TCP uses cumulative; SACK is an option, not the default.",
     "<b>ACK x</b> in TCP = &lsquo;I have everything up to and including "
     "byte x&minus;1&rsquo;. <b>SACK</b> additionally lists received "
     "non-contiguous ranges; requires negotiation."),
    ("Connectionless vs unreliable",
     "UDP is both, but not synonymously.",
     "<b>Connectionless:</b> no handshake / state. <b>Unreliable:</b> "
     "no delivery guarantee. UDP happens to be both; they are separate "
     "properties."),
    ("Authoritative vs recursive DNS",
     "Often swapped.",
     "<b>Authoritative server</b> is the source of truth for a zone. "
     "<b>Recursive resolver</b> walks the tree on the client&rsquo;s "
     "behalf, may cache."),
]))
story.append(PageBreak())

story.append(Paragraph("Definition drift: a worked example", H2))
story.append(callout(
    "trap",
    "Loose answer (typical, scores 1/4)",
    "<i>Q: What is the difference between flow control and congestion "
    "control in TCP?</i><br/><br/>"
    "&ldquo;Flow control and congestion control both prevent the "
    "network from being overloaded. TCP uses both to make sure the "
    "data is sent at the right speed.&rdquo;<br/><br/>"
    "<b>Why this scores 1/4.</b> The answer claims they both protect "
    "the network &mdash; <b>wrong</b>. It does not name the controlling "
    "windows (rwnd, cwnd). It does not identify the entity each protects. "
    "It is true in spirit but technically incorrect."))

story.append(callout(
    "fix",
    "Marker-pleasing answer (4/4)",
    "&ldquo;<b>Flow control</b> protects the <b>receiver</b> from buffer "
    "overflow: the receiver advertises a receive window <i>rwnd</i> "
    "(in bytes) in every ACK, and the sender must keep "
    "<i>(LastByteSent &minus; LastByteAcked) &le; rwnd</i>.<br/><br/>"
    "<b>Congestion control</b> protects the <b>network</b> (intermediate "
    "routers) from overload: the sender maintains a congestion window "
    "<i>cwnd</i> that grows on successful ACKs and shrinks on loss.<br/><br/>"
    "The effective sending window is <i>min(rwnd, cwnd)</i>. They are "
    "<b>independent</b> mechanisms operating on the same window "
    "variable.&rdquo;<br/><br/>"
    "<i>Why this scores full marks.</i> Names both windows, distinguishes "
    "the protected entity, gives the formula linking them."))
story.append(PageBreak())

# ============================================================
# 5. Family IV — Missing warrant & evidence
# ============================================================
story.append(Paragraph("5.  Family IV — Missing warrant & evidence", H1))
story.append(Paragraph(
    "On any question worth more than 5 marks, the marker is looking for "
    "a <b>structured argument</b>, not a recital of facts. The classical "
    "framework here is <b>Toulmin&rsquo;s model</b>: every argument "
    "should explicitly contain a <i>claim</i>, <i>evidence</i>, and a "
    "<i>warrant</i> connecting the two.", BODY))
story.append(Spacer(1, 6))

toulmin = Table([
    ["CLAIM",     "The position you are taking. One sentence."],
    ["EVIDENCE",  "The factual / numerical / protocol-specific support "
                  "for the claim."],
    ["WARRANT",   "The bridge: <i>why</i> this evidence supports the "
                  "claim. This is the marks-bearing sentence most "
                  "students omit."],
    ["BACKING",   "Optional: the underlying principle (RFC, theorem) "
                  "behind the warrant."],
    ["REBUTTAL",  "Optional but essay-grade: the counter-argument and "
                  "why your position survives it."],
], colWidths=[3 * cm, 12.5 * cm])
toulmin.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (0, -1), PRIMARY),
    ("TEXTCOLOR", (0, 0), (0, -1), white),
    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 10),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("ROWBACKGROUNDS", (1, 0), (-1, -1), [white, SOFT]),
    ("BOX", (0, 0), (-1, -1), 0.5, MUTED),
    ("INNERGRID", (0, 0), (-1, -1), 0.25, HexColor("#cbd5e1")),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING", (0, 0), (-1, -1), 6),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
]))
story.append(toulmin)
story.append(Spacer(1, 8))

story.append(Paragraph("Worked example &mdash; UDP vs TCP for video", H3))
story.append(callout(
    "trap",
    "Claim-only answer (loses ~half the essay marks)",
    "&ldquo;UDP is better for video streaming because it is faster and "
    "does not retransmit lost packets.&rdquo;<br/><br/>"
    "<b>Diagnosis.</b> Claim is present (UDP wins). Evidence is vague "
    "(&lsquo;faster&rsquo; &mdash; faster how?). Warrant is missing "
    "(why does the absence of retransmission help video specifically?). "
    "No backing, no rebuttal. Score: ~3/8."))
story.append(callout(
    "fix",
    "Toulmin-structured answer (full marks)",
    "<b>CLAIM:</b> &lsquo;For real-time video conferencing, UDP is "
    "preferable to TCP as the transport substrate.&rsquo;<br/><br/>"
    "<b>EVIDENCE:</b> &lsquo;TCP retransmits on loss, which adds at "
    "least one RTT of delay before the lost segment is delivered. For a "
    "180&nbsp;ms RTT path, this exceeds the 150&nbsp;ms ITU-T G.114 "
    "interactive-voice budget.&rsquo;<br/><br/>"
    "<b>WARRANT:</b> &lsquo;A retransmitted video frame arriving "
    "&gt;100&nbsp;ms late is useless for playback (it is past its "
    "presentation time). UDP&rsquo;s &lsquo;deliver-or-drop&rsquo; "
    "semantics matches the application&rsquo;s actual loss-tolerance "
    "and latency-intolerance.&rsquo;<br/><br/>"
    "<b>BACKING:</b> &lsquo;This is why RTP/WebRTC sit on UDP rather "
    "than TCP, even though RTP itself adds sequence numbers for "
    "reordering.&rsquo;<br/><br/>"
    "<b>REBUTTAL:</b> &lsquo;HTTP-Adaptive-Streaming (DASH, HLS) does "
    "use TCP for prerecorded video, because pre-buffering masks the "
    "retransmission delay. The TCP-vs-UDP choice depends on whether "
    "the application is interactive.&rsquo;"))
story.append(PageBreak())

# ============================================================
# 6. ELEC3120-specific landmines
# ============================================================
story.append(Paragraph("6.  ELEC3120 lecture-by-lecture landmines", H1))
story.append(Paragraph(
    "These are the high-frequency mistakes the LearningPacer knowledge "
    "base sees most often when students chat with the AI tutor. Sweep "
    "them before each topic appears on the exam.", BODY))
story.append(Spacer(1, 6))

landmines = [
    ("L01 Network fundamentals",
     "&bull; <b>Total delay = d_proc + d_queue + d_trans + d_prop</b>. "
     "Most students drop d_proc and d_queue silently.<br/>"
     "&bull; Confusing &lsquo;packet switching&rsquo; with the "
     "&lsquo;Internet&rsquo; &mdash; circuit switching still exists "
     "(GSM voice). Be precise.<br/>"
     "&bull; Mixing the OSI layer numbers with the TCP/IP 5-layer "
     "ones. State which model you use."),
    ("L02 Web &amp; HTTP",
     "&bull; Persistent vs non-persistent connections: state whether "
     "&lsquo;pipelining&rsquo; is on. <br/>"
     "&bull; HTTP/2 &ne; HTTP/3. HTTP/2 still uses TCP. Only HTTP/3 "
     "moved to QUIC over UDP.<br/>"
     "&bull; DNS: TCP is used for zone transfers and large responses "
     "(&gt;512 B), not <i>never</i>."),
    ("L03 Video streaming",
     "&bull; CDNs reduce latency primarily by reducing <i>distance</i>, "
     "not bandwidth. Don&rsquo;t conflate.<br/>"
     "&bull; DASH adapts at the <i>chunk</i> boundary, not per-packet. "
     "Adaptation lag = chunk duration."),
    ("L05 Transport / UDP &amp; TCP",
     "&bull; UDP <i>does</i> have a checksum &mdash; it is mandatory in "
     "IPv6 and optional in IPv4. Do not write &lsquo;UDP has no error "
     "detection&rsquo;.<br/>"
     "&bull; The 4-tuple (src IP, src port, dst IP, dst port) "
     "identifies a TCP connection; the 2-tuple (dst IP, dst port) "
     "identifies a UDP socket. Different objects."),
    ("L06 TCP basics",
     "&bull; Sequence numbers count <b>bytes</b>, not segments. <br/>"
     "&bull; The 3-way handshake transitions: SYN_SENT &rarr; "
     "ESTABLISHED on client; LISTEN &rarr; SYN_RCVD &rarr; ESTABLISHED "
     "on server.<br/>"
     "&bull; Connection close has 4 segments (FIN, ACK, FIN, ACK), not "
     "2. Half-close exists."),
    ("L07 Congestion control",
     "&bull; TCP Tahoe sets cwnd &larr; 1 on any loss. <br/>"
     "&bull; TCP Reno sets cwnd &larr; cwnd/2 on triple-dup-ACK loss "
     "and ssthresh &larr; cwnd/2; it sets cwnd &larr; 1 only on a "
     "true timeout. Mixing them costs marks every year.<br/>"
     "&bull; AIMD: <b>+1 MSS per RTT</b> in CA, <b>&times;0.5</b> on "
     "loss. State the units."),
    ("L08 Advanced congestion control",
     "&bull; CUBIC is named for its <i>cubic</i> growth in cwnd vs "
     "time-since-loss. Not a polynomial of cwnd itself.<br/>"
     "&bull; BBR estimates BW and RTT independently &mdash; it does "
     "<i>not</i> infer congestion from loss."),
    ("L09 Queue management",
     "&bull; M/M/1: average packets <b>in system</b> = "
     "&rho;/(1&minus;&rho;); average <b>in queue</b> = "
     "&rho;<sup>2</sup>/(1&minus;&rho;). Different formulae &mdash; "
     "check which the question asks.<br/>"
     "&bull; RED drops based on <i>average</i> queue length, not "
     "instantaneous. State this."),
    ("L10 IP",
     "&bull; TTL is decremented at every router (not switch). "
     "Switches operate at L2 and never touch the IP TTL.<br/>"
     "&bull; Fragmentation: only the first fragment carries the "
     "transport header. State the More-Fragments and Offset bits in "
     "your answer."),
    ("L11 BGP",
     "&bull; BGP is <b>path-vector</b>, not distance-vector. Loop "
     "detection is by AS_PATH inspection.<br/>"
     "&bull; Route selection order: highest LOCAL_PREF &gt; shortest "
     "AS_PATH &gt; lowest MED &gt; eBGP&gt;iBGP &gt; lowest IGP cost "
     "to NEXT_HOP &gt; tiebreak by router ID. Memorise the order."),
    ("L12 Internet architecture",
     "&bull; Tier-1 ISPs settlement-free peer; Tier-2 buy transit. "
     "Don&rsquo;t conflate."),
    ("L13 LAN",
     "&bull; Min Ethernet frame is 64 B (excl. preamble) to ensure "
     "collision detection within slot time. Derive from "
     "<i>2&middot;t_prop&middot;R</i> &mdash; do not just memorise."),
    ("L14 Distance vector",
     "&bull; Count-to-infinity: split horizon and poison reverse "
     "<i>mitigate</i> but do not <i>solve</i> for arbitrary topology. "
     "Acknowledge the limitation."),
    ("L15 Link layer",
     "&bull; ARP is request-broadcast, reply-unicast. State both "
     "directions.<br/>"
     "&bull; ARP cache TTL is finite (typically minutes); stale "
     "entries cause silent black-holes."),
    ("L16 Wireless",
     "&bull; Hidden terminal: A and C cannot hear each other but both "
     "can hear B. RTS/CTS mitigates.<br/>"
     "&bull; Exposed terminal is the <i>opposite</i> problem &mdash; "
     "do not confuse them."),
    ("L17 New networks",
     "&bull; SDN separates control and data planes. The controller "
     "sits <i>logically</i> centralised but is often physically "
     "distributed.<br/>"
     "&bull; QUIC is L4; HTTP/3 is L7 above it. They are not the same "
     "thing."),
    ("L18 Security",
     "&bull; TLS provides confidentiality, integrity, and server "
     "authentication. Client authentication is optional (mTLS). State "
     "which you mean.<br/>"
     "&bull; Public-key crypto is used to <b>establish a session "
     "key</b>, not to encrypt the bulk traffic (too slow)."),
]
for title, body in landmines:
    story.append(callout("warn", title, body))
    story.append(Spacer(1, 4))

story.append(PageBreak())

# ============================================================
# 7. Toulmin model template
# ============================================================
story.append(Paragraph("7.  The Toulmin template for long answers", H1))
story.append(Paragraph(
    "Copy this template into your scratch space at the start of any "
    "essay question. Fill the slots before you write the prose. It "
    "<i>guarantees</i> you do not skip the warrant.", BODY))
story.append(Spacer(1, 6))

template = Table([
    ["1. CLAIM",
     "<i>One sentence stating your position.</i><br/>"
     "&nbsp;&nbsp;&rarr; ___________________________________________"],
    ["2. EVIDENCE A",
     "<i>One specific protocol, number, RFC, or formula.</i><br/>"
     "&nbsp;&nbsp;&rarr; ___________________________________________"],
    ["3. EVIDENCE B",
     "<i>A second piece of evidence (a different protocol or layer).</i><br/>"
     "&nbsp;&nbsp;&rarr; ___________________________________________"],
    ["4. WARRANT",
     "<i>The bridge sentence: &lsquo;This evidence supports the claim "
     "because&hellip;&rsquo;</i><br/>"
     "&nbsp;&nbsp;&rarr; ___________________________________________"],
    ["5. BACKING",
     "<i>The deeper principle (end-to-end, layering, fate sharing).</i><br/>"
     "&nbsp;&nbsp;&rarr; ___________________________________________"],
    ["6. REBUTTAL",
     "<i>One counter-argument and one sentence answering it.</i><br/>"
     "&nbsp;&nbsp;&rarr; ___________________________________________"],
    ["7. CONCLUSION",
     "<i>Restate the claim, narrowed by the rebuttal.</i><br/>"
     "&nbsp;&nbsp;&rarr; ___________________________________________"],
], colWidths=[3 * cm, 12.5 * cm])
template.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (0, -1), PRIMARY),
    ("TEXTCOLOR", (0, 0), (0, -1), white),
    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 10),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("ROWBACKGROUNDS", (1, 0), (-1, -1), [white, SOFT]),
    ("BOX", (0, 0), (-1, -1), 0.5, MUTED),
    ("INNERGRID", (0, 0), (-1, -1), 0.25, HexColor("#cbd5e1")),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING", (0, 0), (-1, -1), 6),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
]))
story.append(template)
story.append(Spacer(1, 8))

story.append(callout(
    "tip",
    "Three sentences that signal &lsquo;A-grade thinking&rsquo;",
    "&bull; <b>&lsquo;This relies on the assumption that&hellip;&rsquo;</b> &mdash; "
    "marks Family II.<br/>"
    "&bull; <b>&lsquo;This is supported by the evidence that&hellip;&rsquo;</b> "
    "&mdash; marks Family IV (warrant).<br/>"
    "&bull; <b>&lsquo;A counter-argument is&hellip;, but this fails because"
    "&hellip;&rsquo;</b> &mdash; turns a B-grade essay into an A-grade one."))
story.append(PageBreak())

# ============================================================
# 8. Self-marking checklist
# ============================================================
story.append(Paragraph("8.  Self-marking checklist", H1))
story.append(Paragraph(
    "Use this list <b>after</b> you finish the mock paper, before you "
    "look at the answer key. Tick honestly. Each unticked item is a "
    "predicted mark loss.", BODY))
story.append(Spacer(1, 6))

checklist_groups = [
    ("Arithmetic & units",
     [
         "Every numerical answer has units beside it (bits, bytes, ms, MSS).",
         "Bit&harr;byte conversions are explicit (&times;8 written out).",
         "RTT vs one-way is clearly distinguished in every formula.",
         "Subnet calculations include the &minus;2 for net &amp; broadcast.",
         "Logarithm bases are specified (log<sub>2</sub>, not log).",
     ]),
    ("Assumptions",
     [
         "I have written at least one explicit assumption per scenario.",
         "I have stated whether overhead is included or excluded.",
         "I have stated whether the analysis is steady-state or "
         "transient.",
         "I have stated whether reverse-path ACKs are loss-free.",
         "I have stated whether buffer is finite or infinite.",
     ]),
    ("Definitions",
     [
         "I never wrote &lsquo;flow control&rsquo; when I meant "
         "&lsquo;congestion control&rsquo; (or vice versa).",
         "I distinguished MTU from MSS where both appear.",
         "I distinguished collision domain from broadcast domain.",
         "I named cwnd, rwnd, ssthresh by their precise variable name.",
         "I called BGP &lsquo;path-vector&rsquo;, not "
         "&lsquo;distance-vector&rsquo;.",
     ]),
    ("Argument structure (essay questions)",
     [
         "Every essay starts with an explicit one-sentence claim.",
         "I cited at least two pieces of concrete evidence "
         "(protocols, numbers, RFCs).",
         "I wrote at least one explicit warrant sentence connecting "
         "evidence to claim.",
         "I addressed at least one counter-argument.",
         "I labelled my diagrams (axes, units, time direction).",
     ]),
    ("Answering technique",
     [
         "I read the marks-per-question and matched my length to it.",
         "I identified the model first (Stop-and-Wait, GBN, Reno, "
         "M/M/1, &hellip;) before applying any formula.",
         "I wrote the formula symbolically before substituting.",
         "I sanity-checked the magnitude of the final number.",
         "I left no question completely blank (partial credit > 0).",
     ]),
]

for group_name, items in checklist_groups:
    story.append(Paragraph(group_name, H3))
    for item in items:
        story.append(Paragraph(
            f"&nbsp;&nbsp;&#9744; &nbsp;{item}",
            ParagraphStyle("chk", parent=BODY, fontSize=10,
                           leading=14, spaceAfter=2)))
    story.append(Spacer(1, 6))

story.append(Spacer(1, 8))
story.append(callout(
    "marker",
    "The 5-minute review at the end of every exam",
    "Spend the last 5 minutes flicking through this checklist. "
    "<b>Three traps fixed = roughly one letter grade.</b> The students "
    "who consistently outperform are not the ones who knew more &mdash; "
    "they are the ones who reviewed for traps before submitting."))

story.append(Spacer(1, 0.5 * cm))
story.append(Paragraph(
    "Generated by <b>LearningPacer</b> — your AI virtual TA for "
    "ELEC3120.  HKUST FYP, Group MZ01b-25.  Companion to "
    "&lsquo;ELEC3120 Mock Midterm and Final Examination&rsquo;.  "
    "Version 1, May 2026.", SMALL))


# ---------- Build ----------
def build():
    doc = BaseDocTemplate(
        OUT_PATH,
        pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
        title="ELEC3120 Trap Analysis and Answering Techniques",
        author="LearningPacer FYP — Group MZ01b-25",
        subject="ELEC3120 — exam traps & answering technique guide",
    )
    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height, id="normal")
    cover_template = PageTemplate(
        id="cover", frames=[frame], onPage=cover_page_decorator)
    body_template = PageTemplate(
        id="body", frames=[frame], onPage=page_header_footer)
    doc.addPageTemplates([cover_template, body_template])

    final_story = [story[0]]
    inserted = False
    for item in story[1:]:
        if not inserted and isinstance(item, PageBreak):
            final_story.append(NextPageTemplate("body"))
            final_story.append(item)
            inserted = True
        else:
            final_story.append(item)

    doc.build(final_story)
    print(f"Wrote {OUT_PATH} ({os.path.getsize(OUT_PATH) // 1024} KB)")


if __name__ == "__main__":
    build()
