"""ELEC3120 Mock Midterm + Final Exam PDF generator."""
import os
import sys
sys.path.insert(0, os.path.dirname(__file__))

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.colors import HexColor, black, white
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate,
    Paragraph, Spacer, PageBreak, KeepTogether,
    Table, TableStyle, ListFlowable, ListItem
)

from diagrams import (
    osi_stack_diagram, tcp_handshake_diagram, sliding_window_diagram,
    congestion_control_diagram, subnet_diagram, packet_journey_diagram,
    go_back_n_diagram, queue_management_diagram,
    PRIMARY, ACCENT, MUTED, SOFT, WARN
)

OUT_DIR = ".local/exam-pdfs"
os.makedirs(OUT_DIR, exist_ok=True)
OUT_PATH = os.path.join(OUT_DIR, "ELEC3120_Mock_Midterm_and_Final.pdf")


# ---------- Styles ----------
styles = getSampleStyleSheet()

H1 = ParagraphStyle("H1", parent=styles["Heading1"],
                    fontSize=18, leading=22, textColor=PRIMARY,
                    spaceBefore=4, spaceAfter=10,
                    fontName="Helvetica-Bold")
H2 = ParagraphStyle("H2", parent=styles["Heading2"],
                    fontSize=13, leading=16, textColor=PRIMARY,
                    spaceBefore=14, spaceAfter=6,
                    fontName="Helvetica-Bold")
H3 = ParagraphStyle("H3", parent=styles["Heading3"],
                    fontSize=11, leading=14, textColor=ACCENT,
                    spaceBefore=8, spaceAfter=4,
                    fontName="Helvetica-Bold")
SECTION_LABEL = ParagraphStyle("SL", parent=styles["Normal"],
                               fontSize=8, textColor=white,
                               backColor=PRIMARY,
                               fontName="Helvetica-Bold",
                               leftIndent=4, rightIndent=4,
                               spaceBefore=2, spaceAfter=2)
BODY = ParagraphStyle("Body", parent=styles["BodyText"],
                      fontSize=10, leading=13.5, alignment=TA_JUSTIFY,
                      spaceAfter=4)
Q = ParagraphStyle("Q", parent=BODY, fontSize=10, leading=13.5,
                   leftIndent=0, spaceBefore=6, spaceAfter=4)
ANSWER_LINE = ParagraphStyle("AL", parent=BODY, fontSize=10, leading=18,
                             leftIndent=12, textColor=HexColor("#94a3b8"))
SMALL = ParagraphStyle("Small", parent=BODY, fontSize=8.5, leading=11,
                       textColor=MUTED)
INSTR = ParagraphStyle("Instr", parent=BODY, fontSize=9.5, leading=13,
                       textColor=MUTED, fontName="Helvetica-Oblique",
                       leftIndent=8, rightIndent=8,
                       spaceBefore=4, spaceAfter=8)
COVER_TITLE = ParagraphStyle("CT", parent=styles["Title"],
                             fontSize=24, leading=30, textColor=PRIMARY,
                             alignment=TA_CENTER, fontName="Helvetica-Bold")
COVER_SUB = ParagraphStyle("CS", parent=BODY, fontSize=12, leading=16,
                           alignment=TA_CENTER, textColor=MUTED)
CODE = ParagraphStyle("Code", parent=BODY, fontSize=9, leading=12,
                      fontName="Courier", leftIndent=10, rightIndent=10,
                      backColor=SOFT, spaceBefore=4, spaceAfter=4)


# ---------- Helpers ----------
def page_header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(2 * cm, A4[1] - 1.2 * cm,
                      "ELEC3120  Computer Networks  •  HKUST  •  Mock Exam")
    canvas.drawRightString(A4[0] - 2 * cm, A4[1] - 1.2 * cm,
                           "LearningPacer FYP — Mock Paper v1")
    canvas.line(2 * cm, A4[1] - 1.35 * cm,
                A4[0] - 2 * cm, A4[1] - 1.35 * cm)
    canvas.drawCentredString(A4[0] / 2, 1.2 * cm,
                             f"Page {doc.page}")
    canvas.restoreState()


def cover_page_decorator(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, A4[1] - 1.5 * cm, A4[0], 1.5 * cm, fill=1, stroke=0)
    canvas.setFillColor(white)
    canvas.setFont("Helvetica-Bold", 11)
    canvas.drawString(2 * cm, A4[1] - 1 * cm,
                      "HKUST  •  Department of Electronic & Computer Engineering")
    canvas.setFillColor(PRIMARY)
    canvas.rect(0, 0, A4[0], 0.8 * cm, fill=1, stroke=0)
    canvas.setFillColor(white)
    canvas.setFont("Helvetica", 9)
    canvas.drawCentredString(A4[0] / 2, 0.3 * cm,
                             "Generated by LearningPacer — AI Virtual TA for "
                             "ELEC3120  •  FYP Group MZ01b-25")
    canvas.restoreState()


def section_label(text):
    return Paragraph(f"&nbsp;&nbsp;{text}&nbsp;&nbsp;", SECTION_LABEL)


def q(num, text, marks=None):
    suffix = ""
    if marks is not None:
        suffix = f' &nbsp;<font color="#64748b">[{marks} mark{"s" if marks != 1 else ""}]</font>'
    return Paragraph(f"<b>{num}.</b> &nbsp;{text}{suffix}", Q)


def answer_lines(n=3):
    return [Paragraph("_" * 95, ANSWER_LINE) for _ in range(n)]


def tf_options():
    return Paragraph(
        "&nbsp;&nbsp;&nbsp;&nbsp;◯ True  &nbsp;&nbsp;&nbsp;◯ False",
        BODY)


def mcq_options(opts):
    items = []
    for letter, text in zip("ABCDE", opts):
        items.append(Paragraph(
            f"&nbsp;&nbsp;&nbsp;&nbsp;◯ <b>{letter}.</b> &nbsp;{text}", BODY))
    return items


def fill_blank_input(label="Answer:"):
    return Paragraph(
        f'<font color="#64748b">{label}</font> '
        f'<font color="#cbd5e1">______________________________________________</font>',
        BODY)


def scenario_box(title, body):
    t = Table(
        [[Paragraph(f"<b>{title}</b>", BODY)],
         [Paragraph(body, BODY)]],
        colWidths=[16 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), white),
        ("BACKGROUND", (0, 1), (-1, 1), SOFT),
        ("BOX", (0, 0), (-1, -1), 0.6, ACCENT),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def divider():
    return Spacer(1, 6)


# ---------- Build content ----------
story = []

# ============ COVER ============
story.append(Spacer(1, 5 * cm))
story.append(Paragraph("ELEC3120", COVER_TITLE))
story.append(Paragraph("Computer & Communication Networks", COVER_TITLE))
story.append(Spacer(1, 0.5 * cm))
story.append(Paragraph("Mock Midterm &amp; Final Examination",
                       ParagraphStyle("CT2", parent=COVER_TITLE,
                                      fontSize=18, textColor=ACCENT)))
story.append(Spacer(1, 1.0 * cm))
story.append(Paragraph(
    "A state-of-the-art practice paper in the official HKUST examination "
    "format, covering Lectures 1&ndash;18, with diagrams, scenario problems, "
    "and calculation questions modelled after past ELEC3120 papers.",
    COVER_SUB))
story.append(Spacer(1, 1.2 * cm))

cover_meta = Table([
    ["Course", "ELEC3120 — Computer & Communication Networks"],
    ["Department", "Electronic & Computer Engineering, HKUST"],
    ["Format", "Closed book.  Calculator allowed.  No phones."],
    ["Sections",
     "A — Mock Midterm  (90 min, 100 marks, L01–L09)\n"
     "B — Mock Final    (180 min, 150 marks, all lectures)"],
    ["Question types",
     "True/False  •  MCQ  •  Fill-in-blank  •  Short answer  •\n"
     "Scenario analysis  •  Calculations  •  Long essay  •  Diagrams"],
    ["Authoring", "LearningPacer Virtual TA  •  FYP Group MZ01b-25"],
], colWidths=[3.5 * cm, 12 * cm])
cover_meta.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (0, -1), SOFT),
    ("TEXTCOLOR", (0, 0), (0, -1), PRIMARY),
    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ("FONTSIZE", (0, 0), (-1, -1), 9.5),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ("TOPPADDING", (0, 0), (-1, -1), 6),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ("LINEBELOW", (0, 0), (-1, -2), 0.3, HexColor("#cbd5e1")),
]))
story.append(cover_meta)

story.append(Spacer(1, 1.2 * cm))
story.append(Paragraph(
    "&#9888; <b>Important.</b>  This paper is generated by an AI tutor as "
    "study material.  It is <b>not</b> an official HKUST examination and is "
    "<b>not</b> endorsed by the course coordinator.  Use as practice only.",
    SMALL))
story.append(PageBreak())

# ============ INSTRUCTIONS ============
story.append(Paragraph("Instructions to Candidates", H1))
story.append(Paragraph(
    "Read every instruction before you write anything. <b>Markers will "
    "deduct for sloppy answers even when the final value is correct.</b>",
    BODY))
story.append(Spacer(1, 0.3 * cm))

instr_items = [
    "Write your <b>Student ID</b> and <b>Name</b> on every answer booklet.",
    "<b>Show all working</b> for calculation questions. An answer with no "
    "working will receive at most 30% of the marks even if numerically "
    "correct.",
    "<b>State all assumptions explicitly</b> when a question is open-ended "
    "(e.g. ignoring header overhead, assuming symmetric RTT, etc.). "
    "Hidden assumptions cost you marks.",
    "<b>Units matter.</b>  Always include units (bytes, bits, seconds, "
    "ms, MSS) in numerical answers.  A unitless answer is treated as "
    "ambiguous and may be rejected.",
    "For <b>True/False</b>, you must <i>justify</i> in one sentence "
    "(unless the question is marked &ldquo;no justification needed&rdquo;).",
    "For <b>scenario</b> questions, <b>identify the model first</b> "
    "(e.g. Stop-and-Wait vs Sliding Window vs TCP Reno) before applying "
    "any formula. Wrong model = wrong answer regardless of arithmetic.",
    "<b>Diagrams</b> must be labelled (axes, units, time direction). "
    "An unlabelled diagram earns 0 marks.",
    "<b>Negative signs and off-by-one errors</b> are the leading source "
    "of lost marks every year.  Slow down on the arithmetic.",
]
story.append(ListFlowable(
    [ListItem(Paragraph(t, BODY), leftIndent=14) for t in instr_items],
    bulletType="1", start="1"))

story.append(Spacer(1, 0.5 * cm))
story.append(Paragraph(
    "Refer to the companion document <b><i>&ldquo;ELEC3120 Trap Analysis "
    "&amp; Answering Techniques&rdquo;</i></b> for a deeper guide on "
    "common pitfalls (assumption gaps, definition slippage, missing "
    "warrant/evidence) before attempting this paper.", INSTR))

story.append(PageBreak())

# ============================================================
# SECTION A — MOCK MIDTERM
# ============================================================
story.append(section_label("SECTION  A"))
story.append(Paragraph("Mock Midterm Examination", H1))
story.append(Paragraph(
    "<b>Duration:</b> 90 minutes &nbsp;|&nbsp; <b>Total:</b> 100 marks "
    "&nbsp;|&nbsp; <b>Coverage:</b> Lectures 1&ndash;9",
    SMALL))
story.append(Spacer(1, 0.3 * cm))
story.append(Paragraph(
    "Section A1 — True / False (10 &times; 1 = 10 marks).  "
    "Section A2 — MCQ (10 &times; 2 = 20 marks).  "
    "Section A3 — Fill in the blanks (10 &times; 1 = 10 marks).  "
    "Section A4 — Short answer (5 &times; 4 = 20 marks).  "
    "Section A5 — Scenario / Calculation (2 &times; 10 = 20 marks).  "
    "Section A6 — Long answer (1 &times; 20 = 20 marks).",
    INSTR))

# ---- A1: True/False ----
story.append(Paragraph("A1.  True or False", H2))
story.append(Paragraph(
    "Circle one. <b>One sentence justification required for each.</b>",
    INSTR))

tf_questions = [
    "UDP guarantees in-order delivery of datagrams within a single flow.",
    "In TCP, the receiver advertises its receive window (rwnd) using bytes, "
    "not segments.",
    "When a router observes congestion, the IP header has a dedicated "
    "field (ECN) that allows the router to <i>mark</i> a packet rather "
    "than drop it.",
    "Persistent HTTP/1.1 with pipelining is functionally equivalent to "
    "HTTP/2 multiplexing, because both reuse the same TCP connection.",
    "A router with three subnets attached needs exactly three IP "
    "addresses (one per interface) and exactly one MAC address (router-wide).",
    "In Go-Back-N, the receiver must buffer out-of-order packets to "
    "minimise retransmission.",
    "TCP slow start grows the congestion window <i>exponentially</i> per "
    "RTT, but only after a successful 3-way handshake completes.",
    "For a network with bandwidth <i>B</i> bps and one-way propagation "
    "delay <i>d</i> seconds, the bandwidth-delay product equals "
    "<i>2&times;B&times;d</i> bits.",
    "DNS queries always use UDP and never use TCP.",
    "If a TCP segment carrying ACK <i>x</i> is lost but a later segment "
    "with ACK <i>y &gt; x</i> arrives, the sender can still infer that "
    "all bytes up to <i>y&minus;1</i> were received correctly.",
]
for i, qtext in enumerate(tf_questions, 1):
    story.append(q(f"A1.{i}", qtext, 1))
    story.append(tf_options())
    story.append(Paragraph(
        "&nbsp;&nbsp;&nbsp;&nbsp;<i>Justify:</i> "
        "<font color='#cbd5e1'>"
        "______________________________________________________________"
        "</font>", BODY))
    story.append(divider())

story.append(PageBreak())

# ---- A2: MCQ ----
story.append(Paragraph("A2.  Multiple Choice", H2))
story.append(Paragraph(
    "Circle the <b>single best</b> answer.  Penalty for unanswered: 0.  "
    "No partial credit.", INSTR))

mcq_qs = [
    ("Which of the following layers in the TCP/IP 5-layer model is "
     "responsible for end-to-end reliable delivery?",
     ["Physical", "Data Link", "Network", "Transport", "Application"]),
    ("Consider four nodes in series: A &mdash; R1 &mdash; R2 &mdash; B. "
     "Each link has bandwidth 100 Mbps, propagation delay 1 ms, "
     "and transmission delay (per packet) 0.1 ms.  What is the minimum "
     "end-to-end latency for a 1500-byte packet, ignoring queuing?",
     ["0.3 ms", "3.0 ms", "3.3 ms", "4.3 ms", "30 ms"]),
    ("In TCP Reno, when 3 duplicate ACKs are received, the congestion "
     "window is set to:",
     ["1 MSS",
      "ssthresh + 3 MSS",
      "ssthresh / 2",
      "cwnd / 2 (and ssthresh becomes cwnd / 2)",
      "cwnd / 4"]),
    ("Which of the following is <b>NOT</b> a function of the TCP "
     "transport layer?",
     ["Multiplexing/demultiplexing using port numbers",
      "Reliable in-order byte stream",
      "End-to-end congestion control",
      "Hop-by-hop routing decisions",
      "Flow control via the receive window"]),
    ("DNS resolution for <tt>www.example.com</tt> requires recursive "
     "lookup.  Assuming the local resolver has no cached entries and "
     "must walk the entire hierarchy, the <b>minimum</b> number of DNS "
     "messages exchanged (queries + responses) is:",
     ["2", "4", "6", "8", "10"]),
    ("A subnet 192.168.10.0/26 contains how many <b>usable host</b> "
     "addresses?",
     ["62", "63", "64", "126", "256"]),
    ("Which CSMA/CD condition must hold for a station to detect a "
     "collision <i>before</i> finishing transmission?",
     ["Frame size &gt; 2 &times; t_prop &times; bandwidth",
      "Frame size &lt; 2 &times; t_prop &times; bandwidth",
      "Frame size = bandwidth / t_prop",
      "Bandwidth &times; t_prop &lt; 1 byte",
      "There is no such requirement"]),
    ("Pick the <b>most accurate</b> statement about HTTP/2:",
     ["It eliminates the need for TCP congestion control.",
      "It uses UDP rather than TCP.",
      "It allows multiple concurrent requests over a single TCP "
      "connection without head-of-line blocking at the HTTP layer.",
      "It always uses TLS encryption by RFC mandate.",
      "It removes the need for caching headers."]),
    ("A FIFO queue has service rate µ = 1000 pkt/s and arrivals follow "
     "a Poisson process with mean rate &lambda; = 800 pkt/s.  Using "
     "M/M/1 analysis, the average number of packets in the queue is:",
     ["0.8", "4.0", "5.0", "<b>4.0 (excluding the one in service)</b>",
      "Cannot be determined without buffer size"]),
    ("Which routing algorithm category does BGP belong to?",
     ["Link-state, intra-domain",
      "Distance-vector, intra-domain",
      "Path-vector, inter-domain",
      "Source routing, inter-domain",
      "Flooding, intra-domain"]),
]
for i, (qtext, opts) in enumerate(mcq_qs, 1):
    story.append(q(f"A2.{i}", qtext, 2))
    for opt in mcq_options(opts):
        story.append(opt)
    story.append(divider())

story.append(PageBreak())

# ---- A3: Fill in blanks ----
story.append(Paragraph("A3.  Fill in the Blanks", H2))
story.append(Paragraph(
    "One word, number, acronym, or short phrase per blank.  Spelling and "
    "casing of acronyms count.", INSTR))

fb_questions = [
    ("In the OSI model, the layer that provides logical end-to-end "
     "communication between processes is the ________ layer."),
    ("The IPv4 header field that prevents packets from looping forever "
     "is called ________ (3 letters)."),
    ("TCP&rsquo;s slow start exits and switches to congestion avoidance "
     "when cwnd reaches the value of ________ ."),
    ("Stop-and-Wait achieves a maximum utilisation of "
     "U = L / (L + 2 &middot; ________ &middot; R) where L is frame size "
     "in bits and R is bandwidth."),
    ("In HTTP/1.1, the header that lets the server return a 304 Not "
     "Modified to save bandwidth is called <i>If-Modified-Since</i> "
     "or <i>If-None-Match</i> (the latter compares an ________ tag)."),
    ("The minimum Ethernet frame size is ________ bytes (excluding the "
     "preamble and SFD)."),
    ("A routing table entry that matches the longest prefix is selected "
     "based on the principle known as ________ ________ matching."),
    ("In TCP Reno, the window evolution after a single triple-duplicate "
     "ACK loss event reduces cwnd to roughly ________ of its previous "
     "value (express as a fraction)."),
    ("AIMD stands for ________ Increase ________ Decrease."),
    ("The DNS record type that maps a hostname to its canonical name is "
     "________ ."),
]
for i, qtext in enumerate(fb_questions, 1):
    story.append(q(f"A3.{i}", qtext, 1))
    story.append(fill_blank_input())
    story.append(divider())

story.append(PageBreak())

# ---- A4: Short answer ----
story.append(Paragraph("A4.  Short Answer", H2))
story.append(Paragraph(
    "Two to four sentences.  Markers reward <b>precise</b> wording over "
    "long-winded answers.", INSTR))

sa = [
    ("Distinguish between <b>flow control</b> and <b>congestion "
     "control</b> in TCP.  In your answer, identify which entity each "
     "mechanism protects from overload.", 4),
    ("State the three pieces of state a TCP sender must maintain to "
     "implement Fast Retransmit / Fast Recovery, and explain briefly "
     "what each is used for.", 4),
    ("Why is the <b>checksum</b> in UDP described as &ldquo;optional yet "
     "mandatory in IPv6&rdquo;?  Answer in 2 sentences.", 4),
    ("Explain in one sentence each: (a) the difference between a "
     "<b>broadcast</b> domain and a <b>collision</b> domain; "
     "(b) which Layer-2 device defines each.", 4),
    ("Suppose a host receives a TCP segment with sequence number 5001 "
     "and the previously-received cumulative ACK was for byte 4500. "
     "There is a 200-byte gap in between.  Describe what the receiver "
     "should do, and what ACK it sends back.", 4),
]
for i, (qtext, marks) in enumerate(sa, 1):
    story.append(q(f"A4.{i}", qtext, marks))
    for line in answer_lines(4):
        story.append(line)
    story.append(divider())

story.append(PageBreak())

# ---- A5: Scenario / Calculation ----
story.append(Paragraph("A5.  Scenario &amp; Calculation", H2))
story.append(Paragraph(
    "Each scenario carries 10 marks split between (a) modelling, "
    "(b) calculation with shown working, and (c) interpretation.  "
    "<b>State your assumptions.</b>", INSTR))

# A5.1 — sliding window
story.append(scenario_box(
    "Scenario A5.1 — Long-fat-pipe with sliding window",
    "Alice in Hong Kong is uploading a 50 MB video to a server in "
    "London.  The end-to-end bandwidth is <b>100 Mbps</b>, the round-trip "
    "time is <b>180 ms</b>, and TCP MSS is <b>1460 bytes</b>.  Assume "
    "no packet loss and that her link is the bottleneck.  Ignore TCP/IP "
    "header overhead in the data computation."))
story.append(Spacer(1, 4))
story.append(sliding_window_diagram())
story.append(q("A5.1(a)",
               "Compute the bandwidth-delay product (BDP) of this path "
               "in <b>bytes</b> and convert it to a number of MSS-sized "
               "segments.", 3))
for line in answer_lines(4):
    story.append(line)
story.append(q("A5.1(b)",
               "TCP receive window scaling allows windows up to "
               "1 GB.  What window size (in bytes and in MSS) does Alice "
               "need to fully utilise the link?  What window does the "
               "stock 16-bit rwnd field allow without scaling, and what "
               "fraction of bandwidth would she achieve with that?", 4))
for line in answer_lines(5):
    story.append(line)
story.append(q("A5.1(c)",
               "Briefly comment: at this BDP, what other phenomenon "
               "(besides window size) is the most likely throughput "
               "bottleneck for a real upload?", 3))
for line in answer_lines(3):
    story.append(line)

story.append(PageBreak())

# A5.2 — Subnetting
story.append(scenario_box(
    "Scenario A5.2 — Subnet allocation for a campus department",
    "The HKUST Department of ECE has been delegated the IPv4 prefix "
    "<b>203.0.113.0/24</b> by the campus IT.  You must sub-allocate "
    "to three labs:  <b>Lab A</b> needs ~50 hosts, <b>Lab B</b> needs "
    "~25 hosts, and <b>Lab C</b> needs ~10 hosts.  All labs must be in "
    "<b>contiguous</b> address space and you must avoid waste."))
story.append(Spacer(1, 4))
story.append(subnet_diagram())
story.append(q("A5.2(a)",
               "Determine the smallest CIDR prefix length and the exact "
               "address range for each lab.  Show the prefix calculation.",
               5))
for line in answer_lines(6):
    story.append(line)
story.append(q("A5.2(b)",
               "How many usable host addresses are wasted across the "
               "three sub-allocations?  Justify with a short calculation.",
               3))
for line in answer_lines(3):
    story.append(line)
story.append(q("A5.2(c)",
               "Could you save further address space by using a "
               "non-contiguous allocation?  Explain why or why not in "
               "one sentence.", 2))
for line in answer_lines(2):
    story.append(line)

story.append(PageBreak())

# ---- A6: Long answer ----
story.append(Paragraph("A6.  Long Answer (Essay)", H2))
story.append(Paragraph(
    "Write a structured response. Markers expect: (1) a clear "
    "<b>claim</b>, (2) supporting <b>evidence</b> with named protocols "
    "or numbers, and (3) a <b>warrant</b> linking evidence to claim. "
    "Bullet-only answers cannot earn full marks.", INSTR))

story.append(q("A6.1",
               "Compare and contrast the design philosophies of <b>TCP "
               "Tahoe</b>, <b>TCP Reno</b>, and <b>TCP CUBIC</b>. "
               "Your answer should include: (i) how each reacts to a "
               "single packet loss, (ii) how each scales on a long-fat "
               "pipe (large BDP), and (iii) under what real-world "
               "deployment scenario each variant remains a sensible "
               "choice today.  A labelled cwnd-vs-time sketch is "
               "expected.", 20))
story.append(Spacer(1, 4))
story.append(congestion_control_diagram())
story.append(Paragraph(
    "<b>Use the space below.  Continue on a separate sheet if needed.</b>",
    BODY))
for line in answer_lines(18):
    story.append(line)

story.append(PageBreak())

# ============================================================
# SECTION B — MOCK FINAL
# ============================================================
story.append(section_label("SECTION  B"))
story.append(Paragraph("Mock Final Examination", H1))
story.append(Paragraph(
    "<b>Duration:</b> 180 minutes &nbsp;|&nbsp; <b>Total:</b> 150 marks "
    "&nbsp;|&nbsp; <b>Coverage:</b> all lectures (L01&ndash;L18)",
    SMALL))
story.append(Spacer(1, 0.3 * cm))
story.append(Paragraph(
    "Section B1 — True/False (15 &times; 1 = 15 marks).  "
    "Section B2 — MCQ (10 &times; 2 = 20 marks).  "
    "Section B3 — Fill-in (10 &times; 1.5 = 15 marks).  "
    "Section B4 — Short answer (5 &times; 5 = 25 marks).  "
    "Section B5 — Scenario / Calculation (3 &times; 10 = 30 marks).  "
    "Section B6 — Long essay (1 &times; 25 = 25 marks).  "
    "Section B7 — Diagram analysis (1 &times; 20 = 20 marks).",
    INSTR))

# ---- B1 T/F ----
story.append(Paragraph("B1.  True or False", H2))
story.append(Paragraph(
    "No justification required &mdash; circle only.", INSTR))

b1 = [
    "BGP uses path attributes such as AS_PATH and LOCAL_PREF to choose "
    "between routes.",
    "In a wireless 802.11 network, the hidden-terminal problem arises "
    "even when CSMA/CA with RTS/CTS is enabled.",
    "The IP TTL field is decremented by every device that <i>forwards</i> "
    "the packet, including layer-2 switches.",
    "DHCP uses port 67 (server) and port 68 (client) over UDP.",
    "ARP messages are sent inside an Ethernet frame whose EtherType "
    "field is 0x0806.",
    "In RED (Random Early Detection), the drop probability depends on "
    "the <i>instantaneous</i> queue length.",
    "ICMP echo (ping) and traceroute share the same transport-layer "
    "protocol number.",
    "Distance-vector routing converges in O(diameter) rounds in the "
    "absence of failures.",
    "TLS 1.3 has eliminated the round-trip needed for resumption "
    "compared to TLS 1.2.",
    "A switch with full-duplex ports does <b>not</b> need CSMA/CD.",
    "Network Address Translation (NAT) breaks the end-to-end principle "
    "because it requires application-layer awareness for every protocol.",
    "In QUIC, the transport-layer encryption removes the need for TLS.",
    "When a host with no default gateway sends an ARP request for an "
    "off-subnet IP, it will receive a reply only if the router has "
    "Proxy ARP enabled.",
    "Two TCP connections from the same client IP/port to the same "
    "server IP can coexist if their destination ports differ.",
    "In an Ethernet collision domain with <i>n</i> active stations, the "
    "throughput per station is bounded above by <i>1/n</i> of the line "
    "rate even with perfect MAC fairness.",
]
for i, t in enumerate(b1, 1):
    story.append(q(f"B1.{i}", t, 1))
    story.append(tf_options())
    story.append(divider())

story.append(PageBreak())

# ---- B2 MCQ ----
story.append(Paragraph("B2.  Multiple Choice", H2))
b2 = [
    ("In a distance-vector protocol with split horizon, when link A&ndash;B "
     "fails, the count-to-infinity problem is:",
     ["Always avoided",
      "Avoided only when poisoned reverse is also enabled",
      "Avoided in two-node topologies but possible with 3+ nodes",
      "Avoided only on links with synchronous updates",
      "Independent of split horizon"]),
    ("Which of the following is the BGP attribute most directly used to "
     "implement traffic engineering between an AS and its customers?",
     ["AS_PATH",
      "MED (Multi-Exit Discriminator)",
      "LOCAL_PREF",
      "NEXT_HOP",
      "ORIGIN"]),
    ("In an 802.11 BSS, the inter-frame spacing relationship is:",
     ["SIFS &lt; PIFS &lt; DIFS",
      "DIFS &lt; PIFS &lt; SIFS",
      "PIFS &lt; SIFS &lt; DIFS",
      "DIFS = SIFS = PIFS",
      "SIFS &gt; PIFS &gt; DIFS"]),
    ("A network with bandwidth 1 Gbps and propagation delay 5 ms uses "
     "TCP with MSS = 1500 B.  The minimum sender window (in MSS) "
     "needed to fully utilise this link is closest to:",
     ["417 MSS", "833 MSS", "1042 MSS", "5208 MSS", "10417 MSS"]),
    ("In CUBIC TCP, the cwnd evolution between two consecutive loss "
     "events is best described as:",
     ["Linear in time",
      "Exponential in time",
      "Cubic function of time elapsed since last loss",
      "Quadratic function of cwnd",
      "Constant — CUBIC fixes cwnd between losses"]),
    ("Which combination of fields uniquely identifies a TCP <b>connection</b> "
     "at an end host?",
     ["(src IP, dst IP)",
      "(src port, dst port)",
      "(src IP, dst IP, protocol)",
      "(src IP, src port, dst IP, dst port)",
      "(src MAC, dst MAC, src port, dst port)"]),
    ("A host sends a 1500-byte IP datagram into a link with MTU 600 B. "
     "Ignoring options, how many fragments are produced?",
     ["1", "2", "3", "4", "Cannot fragment — packet dropped"]),
    ("In a SDN architecture, the role of the <b>controller</b> is to:",
     ["Forward packets in the fast path",
      "Compute and install forwarding rules in the data plane",
      "Replace the link layer",
      "Encrypt all traffic",
      "Provide DNS resolution"]),
    ("Which of the following statements about HTTP/3 is correct?",
     ["It runs over TCP with TLS 1.3.",
      "It runs over QUIC, which uses UDP at the network layer.",
      "It runs over QUIC, which is itself a transport-layer protocol "
      "above UDP.",
      "It is identical to HTTP/2 except for header compression.",
      "It deprecates the use of TLS."]),
    ("Public-key cryptography in TLS is primarily used to:",
     ["Encrypt all bulk application data for performance reasons",
      "Establish a shared symmetric session key and authenticate "
      "the server",
      "Compress the payload",
      "Replace the need for symmetric ciphers entirely",
      "Provide flow control"]),
]
for i, (qt, opts) in enumerate(b2, 1):
    story.append(q(f"B2.{i}", qt, 2))
    for opt in mcq_options(opts):
        story.append(opt)
    story.append(divider())

story.append(PageBreak())

# ---- B3 Fill in blanks ----
story.append(Paragraph("B3.  Fill in the Blanks", H2))
b3 = [
    "An IPv6 address is ________ bits long, four times the length of "
    "IPv4.",
    "The Ethernet preamble is ________ bytes long and is used by the "
    "receiver for clock synchronisation.",
    "BGP uses TCP port ________ for its control connections.",
    "A router using Dijkstra&rsquo;s algorithm in OSPF must have ________ "
    "knowledge of the topology, distinguishing it from distance-vector "
    "routing.",
    "The Nyquist sampling theorem states that to faithfully reconstruct "
    "a signal of maximum frequency <i>f</i>, the sampling rate must be "
    "at least ________ <i>f</i>.",
    "In a leaky-bucket traffic shaper with rate <i>r</i> and bucket "
    "depth <i>b</i>, the maximum number of bytes that can leave in any "
    "interval of length <i>t</i> is bounded above by ________ .",
    "TCP uses an exponential backoff multiplier of ________ for "
    "successive retransmission timeouts.",
    "The Wi-Fi protocol that defines beacon frames, association, and "
    "disassociation is IEEE ________ .",
    "A Layer-2 broadcast frame uses the destination MAC address ________ .",
    "In TLS 1.3 a session may be resumed in ________ -RTT, eliminating "
    "the full handshake.",
]
for i, t in enumerate(b3, 1):
    story.append(q(f"B3.{i}", t, 1.5))
    story.append(fill_blank_input())
    story.append(divider())

story.append(PageBreak())

# ---- B4 Short answer ----
story.append(Paragraph("B4.  Short Answer", H2))
b4 = [
    ("Explain why <b>BGP</b> is described as a <i>policy-based</i> "
     "routing protocol rather than a shortest-path one.  Give one "
     "concrete example of a policy that two ASes might enforce.", 5),
    ("Compare the <b>fairness</b> guarantees of TCP Reno and CUBIC "
     "when many flows with very different RTTs share a bottleneck.  "
     "Which is more RTT-fair, and why?", 5),
    ("Describe the role of <b>ARP</b> in the journey of an IP packet "
     "between two hosts on the same Ethernet LAN.  At which step does "
     "ARP fire, and what is its broadcast scope?", 5),
    ("State and briefly justify <b>three</b> design decisions in QUIC "
     "that fix structural issues of TCP+TLS.", 5),
    ("In wireless 802.11, explain why the <b>RTS/CTS</b> mechanism is "
     "considered overhead-heavy for short frames.  At what frame size "
     "does it typically pay off, and why?", 5),
]
for i, (t, m) in enumerate(b4, 1):
    story.append(q(f"B4.{i}", t, m))
    for line in answer_lines(5):
        story.append(line)
    story.append(divider())

story.append(PageBreak())

# ---- B5 Scenarios ----
story.append(Paragraph("B5.  Scenario &amp; Calculation", H2))

# B5.1 Go-Back-N
story.append(scenario_box(
    "Scenario B5.1 — Go-Back-N over a noisy satellite link",
    "A geostationary satellite link has one-way propagation delay of "
    "<b>270 ms</b> and bandwidth <b>2 Mbps</b>.  Frames are 1000 bytes. "
    "An ARQ protocol with sender window N is used.  The link drops 1 in "
    "every 100 frames uniformly at random.  Ignore ACK transmission time."))
story.append(Spacer(1, 4))
story.append(go_back_n_diagram())
story.append(q("B5.1(a)",
               "Compute the per-frame transmission time and the "
               "round-trip time.  Compute the minimum window N* required "
               "for the sender to never idle on a loss-free link.", 4))
for line in answer_lines(4):
    story.append(line)
story.append(q("B5.1(b)",
               "With window N = N* (from part a) and a 1% frame error "
               "rate, what is the expected throughput in Mbps using "
               "Go-Back-N?  State your assumptions and any approximation "
               "you used.", 4))
for line in answer_lines(5):
    story.append(line)
story.append(q("B5.1(c)",
               "Compare qualitatively to Selective Repeat with the same "
               "N: which gains more, and why?", 2))
for line in answer_lines(2):
    story.append(line)

story.append(PageBreak())

# B5.2 Routing
story.append(scenario_box(
    "Scenario B5.2 — Distance-vector convergence",
    "Four routers A, B, C, D are arranged in a line (A&ndash;B&ndash;C&ndash;D) "
    "with all link costs = 1.  All routers run distance-vector routing "
    "with split horizon enabled.  At time t = 0, the link C&ndash;D "
    "fails."))
story.append(q("B5.2(a)",
               "Show the routing tables at A, B, C, D <b>before</b> the "
               "failure, and trace the table updates round-by-round "
               "after the failure until convergence.  Explicitly state "
               "the round in which each router learns the loss.", 6))
for line in answer_lines(8):
    story.append(line)
story.append(q("B5.2(b)",
               "If poison reverse were also enabled, would convergence "
               "be faster, slower, or unchanged in this topology?  "
               "Justify in 2 sentences.", 4))
for line in answer_lines(3):
    story.append(line)

story.append(PageBreak())

# B5.3 Queue
story.append(scenario_box(
    "Scenario B5.3 — Buffer sizing for a router interface",
    "An ISP&rsquo;s 10 Gbps egress link sees an aggregate of 1000 long-lived "
    "TCP Reno flows with average RTT 50 ms.  You must size the router&rsquo;s "
    "FIFO buffer."))
story.append(Spacer(1, 4))
story.append(queue_management_diagram())
story.append(q("B5.3(a)",
               "Apply the classical bandwidth-delay rule (B = C &times; RTT) "
               "to compute a buffer size in bytes.  State the limitation "
               "of this rule when many flows share the link.", 4))
for line in answer_lines(4):
    story.append(line)
story.append(q("B5.3(b)",
               "Apply the Stanford rule (B = C &times; RTT / sqrt(N)) and "
               "compare your answer with part (a).", 4))
for line in answer_lines(4):
    story.append(line)
story.append(q("B5.3(c)",
               "If the operator switches to AQM (RED) instead of "
               "drop-tail, what becomes the dominant goal of buffer "
               "sizing?  One sentence.", 2))
for line in answer_lines(2):
    story.append(line)

story.append(PageBreak())

# ---- B6 Long essay ----
story.append(Paragraph("B6.  Long Essay", H2))
story.append(Paragraph(
    "<b>Structure expected:</b> claim → evidence → warrant → "
    "counter-argument → conclusion.  A bullet-list answer is capped at "
    "60% of the marks.  Diagrams should be labelled.", INSTR))

story.append(q("B6.1",
               "&ldquo;The end-to-end principle, articulated by Saltzer, "
               "Reed and Clark in 1984, is fundamentally violated by "
               "modern internet practices such as NAT, deep packet "
               "inspection, and middleboxes.  In your view, has the "
               "Internet evolved <i>away</i> from its founding design "
               "philosophy, or have these violations been necessary "
               "compromises?&rdquo;\n\n"
               "Argue your position with reference to <b>at least two</b> "
               "specific protocols or technologies discussed in this "
               "course.  Address the counter-argument explicitly.", 25))
for line in answer_lines(22):
    story.append(line)

story.append(PageBreak())

# ---- B7 Diagram analysis ----
story.append(Paragraph("B7.  Diagram Analysis", H2))
story.append(Paragraph(
    "Examine the diagrams below carefully.  All sub-questions refer to "
    "the same scenario.", INSTR))

story.append(packet_journey_diagram())
story.append(Spacer(1, 6))
story.append(tcp_handshake_diagram())
story.append(Spacer(1, 6))
story.append(osi_stack_diagram())

story.append(q("B7.1",
               "Trace the journey of a single TCP segment from Host A "
               "(IP 10.0.0.5) to a server behind Router R2.  At each "
               "device, list <b>which header fields change</b> and "
               "<b>which remain unchanged</b>.  Use a table format.", 8))
for line in answer_lines(8):
    story.append(line)
story.append(q("B7.2",
               "On the TCP handshake diagram, the second message "
               "(SYN+ACK) carries both <i>seq=y</i> and <i>ack=x+1</i>. "
               "Explain in 3 sentences what would go wrong if either "
               "field were missing.", 6))
for line in answer_lines(5):
    story.append(line)
story.append(q("B7.3",
               "Which OSI layer is responsible for the difference "
               "between the &lsquo;packet&rsquo; that leaves Host A and "
               "the &lsquo;frame&rsquo; that travels over the cable to "
               "the Switch?  Name the encapsulation operation and state "
               "two fields the layer adds.", 6))
for line in answer_lines(4):
    story.append(line)

story.append(PageBreak())

# ============ END ============
story.append(Paragraph("End of Mock Examination", H1))
story.append(Paragraph(
    "After completing this paper, review your answers against the "
    "<b>companion document</b> "
    "<i>&ldquo;ELEC3120 Trap Analysis &amp; Answering Techniques&rdquo;</i> "
    "to identify the marker-perspective issues you may have overlooked. "
    "Self-marking with the trap checklist is the single highest-leverage "
    "study activity for this course.", BODY))
story.append(Spacer(1, 0.4 * cm))
story.append(Paragraph(
    "Generated by <b>LearningPacer</b> — your AI virtual TA for "
    "ELEC3120.  HKUST FYP, Group MZ01b-25.  Version 1, "
    "May 2026.", SMALL))


# ---------- Build ----------
def build():
    doc = BaseDocTemplate(
        OUT_PATH,
        pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
        title="ELEC3120 Mock Midterm and Final Examination",
        author="LearningPacer FYP — Group MZ01b-25",
        subject="ELEC3120 Computer Networks — Practice Examination",
    )
    frame = Frame(
        doc.leftMargin, doc.bottomMargin,
        doc.width, doc.height, id="normal")
    cover_template = PageTemplate(
        id="cover", frames=[frame], onPage=cover_page_decorator)
    body_template = PageTemplate(
        id="body", frames=[frame], onPage=page_header_footer)
    doc.addPageTemplates([cover_template, body_template])

    # Inject a switch to body template after cover
    from reportlab.platypus.doctemplate import NextPageTemplate
    final_story = [story[0]]  # spacer
    # The cover content (everything until the first PageBreak) stays on
    # the cover template; right before that PageBreak we switch.
    inserted = False
    for i, item in enumerate(story[1:], 1):
        if not inserted and isinstance(item, PageBreak):
            final_story.append(NextPageTemplate("body"))
            final_story.append(item)
            inserted = True
        else:
            final_story.append(item)

    doc.build(final_story)
    print(f"Wrote {OUT_PATH} ({os.path.getsize(OUT_PATH) // 1024} KB)")


if __name__ == "__main__":
    build()
