'use client';

import React, { useState } from 'react';
import {
  Download,
  FileText,
  Check,
  Loader2,
  Clipboard,
  FileDown,
  FileType,
} from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';

interface ConversationExportProps {
  messages: { role: string; content: string; createdAt?: string }[];
  title: string;
  language: 'en' | 'zh';
}

export function ConversationExport({ messages, title, language }: ConversationExportProps) {
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const formatMarkdown = (): string => {
    const lines: string[] = [];
    lines.push(`# ${title}`);
    lines.push(`> ${language === 'en' ? 'Exported from LearningPacer' : '從 LearningPacer 匯出'} · ${new Date().toLocaleString(language === 'en' ? 'en-US' : 'zh-CN')}`);
    lines.push('');
    lines.push(language === 'en'
      ? '> **ELEC3120 Computer Networking · HKUST**'
      : '> **ELEC3120 電腦網絡 · HKUST**');
    lines.push('');

    for (const msg of messages) {
      const role = msg.role === 'user'
        ? (language === 'en' ? '👤 **You**' : '👤 **你**')
        : '🤖 **LearningPacer**';
      const time = msg.createdAt
        ? ` — *${new Date(msg.createdAt).toLocaleTimeString(language === 'en' ? 'en-US' : 'zh-CN', { hour: '2-digit', minute: '2-digit' })}*`
        : '';

      lines.push(`### ${role}${time}`);
      lines.push('');
      lines.push(msg.content);
      lines.push('');
      lines.push('---');
      lines.push('');
    }

    lines.push(`*${language === 'en' ? 'Generated by LearningPacer · HKUST ELEC3120 Computer Networking' : '由 LearningPacer 生成 · HKUST ELEC3120 電腦網絡'}*`);
    lines.push(`*${new Date().toLocaleDateString(language === 'en' ? 'en-US' : 'zh-CN')}*`);
    return lines.join('\n');
  };

  const formatPlainText = (): string => {
    const sep = '═'.repeat(52);
    const thin = '─'.repeat(40);
    const lines: string[] = [];
    lines.push(sep);
    lines.push(`  ${title}`);
    lines.push(sep);
    lines.push(`${language === 'en' ? 'Exported from LearningPacer' : '從 LearningPacer 匯出'}`);
    lines.push(`${language === 'en' ? 'Date' : '日期'}: ${new Date().toLocaleString(language === 'en' ? 'en-US' : 'zh-CN')}`);
    lines.push(`${language === 'en' ? 'Course' : '課程'}: ELEC3120 Computer Networking`);
    lines.push(sep);
    lines.push('');

    for (const msg of messages) {
      const role = msg.role === 'user'
        ? (language === 'en' ? '[You]' : '[你]')
        : '[LearningPacer]';
      const time = msg.createdAt
        ? ` · ${new Date(msg.createdAt).toLocaleTimeString(language === 'en' ? 'en-US' : 'zh-CN', { hour: '2-digit', minute: '2-digit' })}`
        : '';

      lines.push(`${role}${time}`);
      lines.push(msg.content);
      lines.push(thin);
      lines.push('');
    }

    lines.push(sep);
    lines.push(language === 'en'
      ? '  Generated by LearningPacer · HKUST ELEC3120'
      : '  由 LearningPacer 生成 · HKUST ELEC3120');
    lines.push(sep);

    return lines.join('\n');
  };

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    setExporting(true);
    try {
      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast({
        title: language === 'en' ? '✅ Exported!' : '✅ 匯出成功!',
        description: filename,
      });
    } catch {
      toast({
        title: language === 'en' ? '❌ Export failed' : '❌ 匯出失敗',
        description: language === 'en' ? 'Please try again.' : '請再試一次。',
        variant: 'destructive',
      });
    } finally {
      setTimeout(() => setExporting(false), 500);
    }
  };

  const handleCopyMarkdown = async () => {
    try {
      await navigator.clipboard.writeText(formatMarkdown());
      setCopied(true);
      toast({
        title: language === 'en' ? '✅ Copied!' : '✅ 已複製!',
        description: language === 'en' ? 'Markdown copied to clipboard' : 'Markdown 已複製到剪貼簿',
      });
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast({
        title: language === 'en' ? '❌ Copy failed' : '❌ 複製失敗',
        variant: 'destructive',
      });
    }
  };

  const handleExportMarkdown = () => {
    const content = formatMarkdown();
    const safeTitle = title.replace(/[^a-zA-Z0-9\u4e00-\u9fff]/g, '_').slice(0, 30);
    downloadFile(content, `${safeTitle}.md`, 'text/markdown;charset=utf-8');
  };

  const handleExportText = () => {
    const content = formatPlainText();
    const safeTitle = title.replace(/[^a-zA-Z0-9\u4e00-\u9fff]/g, '_').slice(0, 30);
    downloadFile(content, `${safeTitle}.txt`, 'text/plain;charset=utf-8');
  };

  if (messages.length === 0) return null;

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="ghost"
          size="icon"
          className="h-8 w-8 text-gray-500 hover:text-emerald-600 dark:hover:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-950/30 rounded-lg transition-all duration-200"
          aria-label={language === 'en' ? 'Export conversation' : '匯出對話'}
          disabled={exporting}
        >
          {exporting ? (
            <Loader2 className="h-4 w-4 animate-spin text-emerald-500" />
          ) : (
            <Download className="h-4 w-4" />
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent
        align="end"
        className="w-56 rounded-xl border border-gray-200/80 dark:border-white/10 bg-white dark:bg-[#1e1e1e] shadow-lg shadow-emerald-500/[0.04] p-1.5"
      >
        {/* Header */}
        <div className="px-2 py-1.5 mb-0.5">
          <p className="text-[11px] font-semibold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider">
            {language === 'en' ? 'Export' : '匯出'}
          </p>
        </div>
        <DropdownMenuSeparator className="bg-gray-100 dark:bg-white/[0.06] my-0.5" />

        {/* Copy as Markdown */}
        <DropdownMenuItem
          onClick={handleCopyMarkdown}
          className="gap-3 cursor-pointer rounded-lg px-2.5 py-2 text-[13px] text-gray-700 dark:text-gray-300 hover:bg-emerald-50 dark:hover:bg-emerald-950/40 hover:text-emerald-700 dark:hover:text-emerald-300 transition-colors duration-150 focus:bg-emerald-50 dark:focus:bg-emerald-950/40 focus:text-emerald-700 dark:focus:text-emerald-300"
        >
          {copied ? (
            <div className="h-7 w-7 rounded-lg bg-emerald-100 dark:bg-emerald-900/50 flex items-center justify-center">
              <Check className="h-3.5 w-3.5 text-emerald-600 dark:text-emerald-400" />
            </div>
          ) : (
            <div className="h-7 w-7 rounded-lg bg-gray-100 dark:bg-white/[0.06] flex items-center justify-center group-hover:bg-emerald-100 dark:group-hover:bg-emerald-900/50">
              <Clipboard className="h-3.5 w-3.5 text-gray-500 dark:text-gray-400 group-hover:text-emerald-600 dark:group-hover:text-emerald-400" />
            </div>
          )}
          <div className="flex flex-col">
            <span className="font-medium">
              {copied
                ? (language === 'en' ? 'Copied!' : '已複製！')
                : (language === 'en' ? 'Copy as Markdown' : '複製為 Markdown')}
            </span>
            <span className="text-[11px] text-gray-400 dark:text-gray-500">
              {language === 'en' ? 'Paste anywhere' : '貼上到任意位置'}
            </span>
          </div>
        </DropdownMenuItem>

        {/* Download .md */}
        <DropdownMenuItem
          onClick={handleExportMarkdown}
          className="gap-3 cursor-pointer rounded-lg px-2.5 py-2 text-[13px] text-gray-700 dark:text-gray-300 hover:bg-emerald-50 dark:hover:bg-emerald-950/40 hover:text-emerald-700 dark:hover:text-emerald-300 transition-colors duration-150 focus:bg-emerald-50 dark:focus:bg-emerald-950/40 focus:text-emerald-700 dark:focus:text-emerald-300"
        >
          <div className="h-7 w-7 rounded-lg bg-gray-100 dark:bg-white/[0.06] flex items-center justify-center">
            <FileDown className="h-3.5 w-3.5 text-gray-500 dark:text-gray-400" />
          </div>
          <div className="flex flex-col">
            <span className="font-medium">
              {language === 'en' ? 'Download .md' : '下載 .md'}
            </span>
            <span className="text-[11px] text-gray-400 dark:text-gray-500">
              Markdown {language === 'en' ? 'file' : '檔案'}
            </span>
          </div>
        </DropdownMenuItem>

        {/* Download .txt */}
        <DropdownMenuItem
          onClick={handleExportText}
          className="gap-3 cursor-pointer rounded-lg px-2.5 py-2 text-[13px] text-gray-700 dark:text-gray-300 hover:bg-emerald-50 dark:hover:bg-emerald-950/40 hover:text-emerald-700 dark:hover:text-emerald-300 transition-colors duration-150 focus:bg-emerald-50 dark:focus:bg-emerald-950/40 focus:text-emerald-700 dark:focus:text-emerald-300"
        >
          <div className="h-7 w-7 rounded-lg bg-gray-100 dark:bg-white/[0.06] flex items-center justify-center">
            <FileType className="h-3.5 w-3.5 text-gray-500 dark:text-gray-400" />
          </div>
          <div className="flex flex-col">
            <span className="font-medium">
              {language === 'en' ? 'Download .txt' : '下載 .txt'}
            </span>
            <span className="text-[11px] text-gray-400 dark:text-gray-500">
              {language === 'en' ? 'Plain text file' : '純文字檔案'}
            </span>
          </div>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
